### ISSUE TITLE
applyPathPrefix

### ISSUE THREAD

**Issue by denndk** [thephpleague/flysystem-dropbox#11]
Hi,

My Dropbox integration suddenly broke and I updated to v. 1.0.3. 

I get 301 error when using the API. I broke the issue down to the applyPathPrefix() function. 

Normally I would do this:
```
$filesystem = new Filesystem(new Adapter($client, '/'));
```

This has worked for nearly a year, but it seems that the Dropbox API has a new behaviour, which means it fails to find the a file, because the request path will be with two slashes in the beginning. So instead of /1/metadata/auto/path/to/file.jpg it will be /1/metadata/auto//path/to/file.jpg. 

That doesn't work anymore. 

I can see that the first slash is added in:
```
 public function applyPathPrefix($path)
    {

        $path = parent::applyPathPrefix($path);
        return '/' . rtrim($path, '/');
    }
```
Maybe the code should include a ltrim($path, '/') e.g.
```
return '/' . ltrim(rtrim($path, '/'), '/');

```

**Comment by frankdejonge** [comment]
@denndk did you try pinning it down on 1.0.2? Perhaps there was a regression.

**Comment by frankdejonge** [comment]
I've opened an issue with the dropbox sdk here: https://github.com/dropbox/dropbox-sdk-php/issues/43

**Comment by denndk** [comment]
Hi @frankdejonge ,

Thank you for the quick response. I didn't try it on 1.0.2, but I guess its on the Dropbox API side.

For now I just made a quick fix as described above.
