### ISSUE TITLE
Error when uploading large file around 70MB

### ISSUE THREAD

**Issue by adityaism** [thephpleague/flysystem-dropbox#16]
Error when uploading large file around 70MB. I have set the `memory_limit=-1;` still getting following error

     Out of memory (allocated 84672512) (tried to allocate 70293325 bytes) in /var/www/test.api/vendor/dropbox/dropbox-sdk/lib/Dropbox/Curl.php on line 73

    PHP Fatal error:  Uncaught exception 'ErrorException' with message 'proc_open(): fork failed - Cannot allocate memory' in /var/www/test.api/vendor/symfony/console/Application.php:935`

the sample code for upload 
`            
              
              $path = 'public/'.$filename;
	      $file = fopen($path, 'r');
		$len = 1024; // 1MB is reasonable for me. You can choose anything though, but do not make it too big
		$output = fread( $file, $len );

		while (!feof($file)) {
		    $output .= fread( $file, $len );
		}

		fclose($file);

		$this->cloud->put($filename, $output);`
` 
`

**Comment by frankdejonge** [comment]
@adityaism why aren't you using putStream for this and just using the resource without loading it into memory in its entirety?

**Comment by frankdejonge** [comment]
Also, the fact that you still get an exception although you set the memory limit is not something Flysystem can fix for you.

**Comment by adityaism** [comment]
`putStream` solved it. Thanks.
