### ISSUE TITLE
Too long waiting time

### ISSUE THREAD

**Issue by Kravalg** [thephpleague/flysystem-dropbox#7]
I use [elFinder](https://github.com/Studio-42/elFinder) with Flysystem Dropbox.

I waited 19 seconds to find that the folder is empty.
Stack trace:
```
{"cwd":{"size":0,"ts":1458659319,"read":1,"write":1,"mime":"directory","hash":"fls1_cm96c3plcnpvbnl3b2x1bWluLzIwMTYvMTQ2XzIwMTYvc3RyYXogZ3Jhbmljem5h"
,"name":"straz graniczna","phash":"fls1_cm96c3plcnpvbnl3b2x1bWluLzIwMTYvMTQ2XzIwMTY","volumeid":"fls1_"
},"options":{"path":"rozszerzonywolumin\/rozszerzonywolumin\/2016\/146_2016\/straz graniczna","url":""
,"tmbUrl":"","disabled":["archive","extract","chmod"],"separator":"\/","copyOverwrite":1,"uploadOverwrite"
:1,"uploadMaxSize":9223372036854775807,"dispInlineRegex":"^(?:(?:image|text)|application\/x-shockwave-flash$
)","jpgQuality":100,"archivers":{"create":[],"extract":[],"createext":[]},"uiCmdMap":[],"syncChkAsTs"
:0,"syncMinMs":30000},"files":[],"debug":{"connector":"php","phpver":"7.0.4","time":19.19310593605,"memory"
:"4034Kb \/ 2238Kb \/ 128M","upload":"","volumes":[{"id":"fls1_","name":"flysystem","mimeDetect":"finfo"
,"imgLib":"gd"}],"mountErrors":[]}}
```

I use Flysystem connector.

My connector.minimal.php file:

```
$client = new Client('-----------------------------------------------------------------', '----------------------');
$localAdapter = new DropboxAdapter($client);

$cacheStore = new CacheStore();
$adapter = new CachedAdapter($localAdapter, $cacheStore);
$filesystem = new Filesystem($adapter);

$opts = [
'debug' => 1,
'treeDeep' => 1,
'roots' => [
[
'driver' => 'Flysystem',
'path' => 'rozszerzonywolumin',
'filesystem' => $filesystem
]
]
];
```

In general, all actions based on a sample listing of folders and files is very slow. How can I speed up the loading or otdebazhit which component slows down?

**Comment by frankdejonge** [comment]
@Kravalg Hi, the calls from flysystem are proxied to the dropbox sdk, the time spend here is negligible. Either this is a networking issue, something within the dropbox api or something in elFinder. I know the dropbox api isn't the fastest to respond, but 19 seconds seems too much. Have you tried looking into _where_ the delay is coming from by using a profiler like blackfire.io?

**Comment by Kravalg** [comment]
No, I have not tried, but tried
After updating all dropboks as long answers
What other methods do you offer?

**Comment by frankdejonge** [comment]
@Kravalg I don't understand what you're saying.

**Comment by Kravalg** [comment]
After the upgrade flysystem-dropbox to version 1.0.3, nothing has changed in my situation.
I tried to use blackfire.io, but did not work out
What other methods do you offer?
